---
title: "Quarto et github pages"
description: Showing some neat features of Quarto!
date: today # other options: now, last-modified
author: Olivier Maccaud 
format:
  revealjs:
    code-fold: false
    theme: white
    footer: "OM 2023.07.17"
    chalkboard: true
    navigation-mode: grid
    slide-number: c/t
# bibliography: penguins.bib
# link-citations: yes
# csl: apa-single-spaced.csl
---

# Faire un site Github pages avec Quarto

## Editeur Visual Studio Code

- Selon la structure (Fichiers et répertoires) construite par RStudio.
- Installer une extension à VSC (Visual Studio Code) (CTRL-MAJ-X)
- Quarto 

## Faire un site avec "Github pages" {.scrollable}


### Pour faire simple

- Dans le terminal de RStudio : quarto render
- Explorateur windows : ouvrir C:\\TEXTES\\ECLAIRAGE\\REVEAL_MATH_SLG\\quarto_slg\\math_blog\\math_blog
- Dans windows ouvrir un terminal de commande (administrateur) : cd C:\\TEXTES\\ECLAIRAGE\\REVEAL_MATH_SLG\\quarto_slg\\math_blog\\math_blog
- git init
- git add .
- git commit -m "first commit"
- git branch -M main
- git remote add origin https://github.com/omelectro1/pres_math_1.git
- git push -u origin main

## Dans github

- https://github.com/omelectro1/pres_math_1/settings
- Menu (gauche) "pages"
- Branch "main" "root" -> Save

## Si problème de permissions avec le compte github

-- Dans windows panneau de configuration -> Comptes d'utilisateurs -> Gestionnaire d'identifications -> Informations d'identification Windows
- Effacer les "identifications génériques github"

# Mise à jour du site.

## Avec RStudio

- Modifier les textes dans les fichiers *.qmd
- Enregistrer les changements (CTRL-S)
- Résultat, dans le terminal : quarto render


## Dans le terminal de commande windows : 

- git add .
- git commit -m "SECOND commit"
- git push -u origin main